title: "Exit Status One"
description: "A compilation of information about various interesting and uninteresting topics."
keywords: "Software, Development, Ruby, Jekyll, Sinatra, Linux, Security, Programming, Technology"
tagline: "while : ; do echo 'Tinker, explore, hack, learn...' ; sleep 28800 ; clear ; done"
user: Brenton Earl

baseurl: ""
url: http://www.exitstatusone.com

markdown: rdiscount
permalink: /:title/

category_dir: "categories/"

exclude: [Gemfile, Gemfile.lock, README.md, Rakefile]

gems:
  - jekyll-sitemap

sass:
  style:  :compressed
